.PHONY: deps
deps: bin/goreleaser

bin/goreleaser:
	mkdir -p bin
	wget https://github.com/goreleaser/goreleaser/releases/download/v0.164.0/goreleaser_Linux_x86_64.tar.gz
	tar -C bin -xzf goreleaser*tar.gz goreleaser
	rm goreleaser*tar.gz*